### ISSUE TITLE
licenses compatibility check

### ISSUE THREAD

**Issue by IngwiePhoenix** [nodeshift/license-reporter#319]
I'd like to know which direct licenses my project is possibly subjected to, especially in regards to more or less restrictive licenses, as bundling packages together with tools like WebPack is the equivalent of linking a number of static libraries and object files into the same executable.

In order to stay out of license troubbles, I'd like to know how many licenses I am subjected to. I can then still use the regular reporter to spot out the packages using licenses such as GPLv2 or even GPLv3 which is actually incompatible with MIT and BSD-2-Clause and BSD-3-Clause, as far as I know.

This stuff is rather important, as I may use either
- https://www.globalsign.com/de-de/ssl/ssl-open-source/
Or
- https://letsencrypt.org/

In this situation, I have to be very informed about the licenses used, and therefore choose the license that is compatible with the licenses in use.

**Comment by lambourn** [comment]
@IngwiePhoenix this might be useful https://github.com/codepunkt/webpack-license-plugin

**Comment by helio-frota** [comment]
That seems to be a nice feature to have.
At least a `stdout` warning/error message about the incompatibility between licenses.

(I think the correct way is to show the error message and interrupt the process - nobody wants license troubles)

**Comment by helio-frota** [comment]
We need at least [this issue](https://github.com/HansHammel/license-compatibility-checker/issues/5) fixed before start to use as dependency.

**Comment by lance** [comment]
CLosing this for now as we don't think it is a feature we intend to add to this module.
