### ISSUE TITLE
can't generate more than one "save" file

### ISSUE THREAD

**Issue by oupala** [nodeshift/license-reporter#330]
**Describe the bug**

The CLI does not generated multiple export format file when required.

In addition, it appears that the README file contains an error in an example command, where the `save` keyword is missing.

https://github.com/nodeshift/license-reporter/blob/407f48c8b3bf2bee027d9e424d74349d0ffb2059/README.md#L1088-L1101

**To Reproduce**

1. launch the command `license-reporter save --full-dependency-tree --json licenses.json --yaml licenses.yaml --xml licenses.xml`
2. see that only `licences.json` is created, `licenses.yaml` and `licenses.xml` are missing

**Expected behavior**

3 files in the `licenses` directory:

- licenses.json
- licenses.yaml
- licenses.xml

**Desktop (please complete the following information):**
 - OS: linux
 - Browser n/a
 - Version last one 1.2.1

**Additional context**

**Comment by helio-frota** [comment]
@oupala Thank you for the report.

https://github.com/nodeshift/license-reporter/commit/bb9f11cb315eba11a13d5c93b64f692da866ea3f

New version published right now: https://www.npmjs.com/package/license-reporter

**Comment by oupala** [comment]
My pleasure! Thanks for this useful tool!
