### ISSUE TITLE
Remove issue template -- unnecessary bureaucracy

### ISSUE THREAD

**Issue by helio-frota** [nodeshift/license-reporter#356]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by helio-frota** [comment]
@alexalikiotis  I noticed the issue template file still there 
https://github.com/nodeshift/license-reporter/tree/master/.github

removing that directory fix this issue :+1:

**Comment by alexalikiotis** [comment]
@helio-frota there is only a file called feature_request.md in there (https://github.com/nodeshift/license-reporter/tree/master/.github/ISSUE_TEMPLATE)

**Comment by helio-frota** [comment]
yeah you can remove that `ISSUE_TEMPLATE` directory :+1:

**Comment by helio-frota** [comment]
Thanks! landed here: https://github.com/nodeshift/license-reporter/commit/f7d3e58b13dd5f7360d28b24ec4aefad5f31b6bd
