### ISSUE TITLE
Use npm-audit-ci-wrapper with moderate threshold

### ISSUE THREAD

**Issue by helio-frota** [nodeshift/license-reporter#359]
Example: https://github.com/helio-frota/falta/blob/master/.github/workflows/nodejs-ci-action.yml#L28

Depends on #358

**Comment by helio-frota** [comment]
@alexalikiotis setting to `moderate` instead of `low` seems better, so we don't bother too much with the broken builds for small things.
https://github.com/nodeshift/license-reporter/blob/master/.github/workflows/nodejs-ci-action.yml#L28

**Comment by alexalikiotis** [comment]
Fixed in #363

**Comment by helio-frota** [comment]
Cool, thanks!
